version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  say-hello:
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "aws s3api create-bucket --bucket my-bucket --region us-east-1"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
